name: BoilerPlate

# Trigger the workflow on push to the main branch or any changes to the "gh-pages" branch
on:
  push:
    branches:
      - main  # Replace 'main' with your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository's code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # Specify the version of Node.js you want to use

    # Step 3: Install dependencies using npm
    - name: Install dependencies
      run: npm install

    # Step 4: Build the React app for production
    - name: Build React app
      run: npm run build

    # Step 5: Deploy the production build to the gh-pages branch
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # You can change this if you want to deploy to a different branch
        publish_dir: ./build      # This is the directory where your built React app is located

